### ISSUE TITLE
Create README 

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/python-demo-app#46]
README should contain instructions on how to clone this project and how to run it locally with Scope for Mac/Windows to obtain Scratchpad results. 

Ideally, all integration tests are automatically configured to be ran against our "production" hamburguesía instance, such that when I run them locally I still the full traces in Scratchpad.

**Comment by juan-fernandez** [comment]
closed in https://github.com/scope-demo-app/python-demo-app/commit/9212fa28fb020b2c76ae172d06d7404f3a53aced
